#include <Statements\Command.h>
#include <Statements\Condition.h>
#include <Statements\Factor.h>
#include <Statements\FunctionCall.h>
#include <Statements\FunctionDeclaration.h>
#include <Statements\Order.h>
#include <Statements\Program.h>
#include <Statements\Repeat.h>
#include <Statements\SimpExpr.h>
#include <Statements\Statement.h>
#include <Statements\Term.h>
#include <Statements\VariableAssignment.h>
#include <Statements\VariableDeclaration.h>